#include "sources/gog/GogGenreMap.h"

#include <QHash>

namespace ssv {

namespace {

// Lower-cased GOG genre or tag name (catalog.gog.com's `genres[]` and
// `tags[]` on a product) -> canonical genre. Many GOG tags fold into one
// canonical genre (e.g. Roguelite -> Roguelike). Names verified against the
// catalog's own filter lists (`fullGenresList`, `fullTagsList`).
const QHash<QString, QString>& labelTable()
{
    static const QHash<QString, QString> t{
        {"rpg", "RPG"},
        {"massively multiplayer", "Massively Multiplayer"},
        {"2d", "2D"},
        {"4x", "4X"},
        {"action", "Action"},
        {"adventure", "Adventure"},
        {"arcade", "Arcade"},
        {"atmospheric", "Atmospheric"},
        {"base building", "Base Building"},
        {"beat 'em up", "Beat 'em Up"},
        {"board game", "Board Game"},
        {"building", "Base Building"},
        {"bullet hell", "Shoot 'em Up"},
        {"card game", "Card Game"},
        {"cartoony", "Cartoony"},
        {"casual", "Casual"},
        {"cats", "Animals"},
        {"chess", "Board Game"},
        {"choices matter", "Story Rich"},
        {"choose your own adventure", "Story Rich"},
        {"city builder", "City Builder"},
        {"classic", "Retro"},
        {"comedy", "Comedy"},
        {"cooking", "Life Sim"},
        {"cozy", "Cozy"},
        {"crafting", "Crafting"},
        {"crime", "Crime"},
        {"crossplay", "Multiplayer"},
        {"crpg", "CRPG"},
        {"cyberpunk", "Cyberpunk"},
        {"dark", "Dark"},
        {"dark comedy", "Comedy"},
        {"dating sim", "Dating Sim"},
        {"deckbuilding", "Card Game"},
        {"detective-mystery", "Mystery"},
        {"difficult", "Difficult"},
        {"dinosaurs", "Dinosaurs"},
        {"dog", "Animals"},
        {"dungeon crawler", "Dungeon Crawler"},
        {"dystopian", "Post-Apocalyptic"},
        {"economic", "Management"},
        {"education", "Educational"},
        {"educational", "Educational"},
        {"espionage", "Stealth"},
        {"exploration", "Exploration"},
        {"family friendly", "Family Friendly"},
        {"fantasy", "Fantasy"},
        {"farming", "Farming"},
        {"female protagonist", "Female Protagonist"},
        {"fighting", "Fighting"},
        {"first-person", "First-Person"},
        {"fishing", "Fishing"},
        {"flight", "Flight"},
        {"fmv", "FMV"},
        {"football", "Team Sports"},
        {"fps", "First-Person Shooter"},
        {"free game", "Free To Play"},
        {"funny", "Comedy"},
        {"good old game", "Retro"},
        {"gore", "Gore"},
        {"grand strategy", "Grand Strategy"},
        {"hack and slash", "Hack and Slash"},
        {"hentai", "Sexual Content"},
        {"hidden object", "Hidden Object"},
        {"historical", "Historical"},
        {"horror", "Horror"},
        {"indie", "Indie"},
        {"investigation", "Mystery"},
        {"isometric", "Isometric"},
        {"jrpg", "JRPG"},
        {"lgbtq+", "LGBTQ+"},
        {"lifesim", "Life Sim"},
        {"local co-op", "Co-op"},
        {"local multiplayer", "Multiplayer"},
        {"logic", "Puzzle"},
        {"looter shooter", "Shooter"},
        {"lovecraftian", "Lovecraftian"},
        {"magic", "Fantasy"},
        {"management", "Management"},
        {"managerial", "Management"},
        {"martial arts", "Martial Arts"},
        {"match3", "Match 3"},
        {"medieval", "Medieval"},
        {"metroidvania", "Metroidvania"},
        {"military", "War"},
        {"multiplayer", "Multiplayer"},
        {"multiple endings", "Story Rich"},
        {"mystery", "Mystery"},
        {"mythology", "Mythology"},
        {"narrative", "Story Rich"},
        {"nature", "Nature"},
        {"naval", "Naval"},
        {"ninja", "Martial Arts"},
        {"noir", "Mystery"},
        {"non violent", "Family Friendly"},
        {"nsfw", "Sexual Content"},
        {"nudity", "Nudity"},
        {"off-road", "Racing"},
        {"online-only", "Multiplayer"},
        {"open world", "Open World"},
        {"parody", "Comedy"},
        {"party game", "Party Game"},
        {"perma death", "Roguelike"},
        {"petting dogs", "Animals"},
        {"physics", "Physics"},
        {"pirates", "Pirates"},
        {"pixel graphics", "Pixel Graphics"},
        {"platformer", "Platformer"},
        {"point&click", "Point & Click"},
        {"politics", "Grand Strategy"},
        {"post-apocalyptic", "Post-Apocalyptic"},
        {"programming", "Educational"},
        {"psychological horror", "Horror"},
        {"puzzle", "Puzzle"},
        {"puzzle platformer", "Platformer"},
        {"racing", "Racing"},
        {"rally", "Racing"},
        {"real-time", "Real-Time Strategy"},
        {"realistic", "Realistic"},
        {"relaxing", "Cozy"},
        {"resource management", "Management"},
        {"retro", "Retro"},
        {"rhythm", "Rhythm"},
        {"robots", "Robots"},
        {"roguelike", "Roguelike"},
        {"roguelite", "Roguelike"},
        {"role-playing", "RPG"},
        {"romance", "Romance"},
        {"rts", "Real-Time Strategy"},
        {"sandbox", "Sandbox"},
        {"sci-fi", "Sci-Fi"},
        {"sexual content", "Sexual Content"},
        {"shoot'emup", "Shoot 'em Up"},
        {"shooter", "Shooter"},
        {"simulation", "Simulation"},
        {"sniper", "Shooter"},
        {"soccer", "Team Sports"},
        {"souls-like", "Souls-like"},
        {"space", "Space"},
        {"split screen", "Multiplayer"},
        {"sports", "Sports"},
        {"stealth", "Stealth"},
        {"steampunk", "Steampunk"},
        {"story rich", "Story Rich"},
        {"strategy", "Strategy"},
        {"superhero", "Superhero"},
        {"supernatural", "Supernatural"},
        {"survival", "Survival"},
        {"survival horror", "Horror"},
        {"tabletop", "Board Game"},
        {"tactical", "Tactical"},
        {"tactical rpg", "Tactical RPG"},
        {"tanks", "Tanks"},
        {"team sport", "Team Sports"},
        {"text-based", "Text-Based"},
        {"third person", "Third-Person"},
        {"time manipulation", "Time Travel"},
        {"top-down", "Top-Down"},
        {"tower defense", "Tower Defense"},
        {"trading", "Management"},
        {"trains", "Trains"},
        {"transportation", "Trains"},
        {"turn-based", "Turn-Based"},
        {"twin stick shooter", "Shooter"},
        {"typing", "Educational"},
        {"underwater", "Underwater"},
        {"vampire", "Supernatural"},
        {"vikings", "Mythology"},
        {"violent", "Violent"},
        {"virtual life", "Life Sim"},
        {"visual novel", "Visual Novel"},
        {"vr", "VR"},
        {"walking simulator", "Walking Simulator"},
        {"war", "War"},
        {"werewolves", "Supernatural"},
        {"western", "Western"},
        {"world war i", "War"},
        {"world war ii", "War"},
        {"zombies", "Zombies"},
    };
    return t;
}

// Canonical genre -> the catalog filter that lists it: a top-level genre
// (`genres=in:<slug>`) where GOG has one, otherwise a tag
// (`tags=in:<slug>`). catalog.gog.com answers an unknown slug with an empty
// listing rather than an error, so a wrong slug here only wastes a request.
const QHash<QString, GogGenreMap::CatalogFilter>& filterTable()
{
    static const QHash<QString, GogGenreMap::CatalogFilter> t{
        {"Action", {"genres", "action"}},
        {"Adventure", {"genres", "adventure"}},
        {"Casual", {"tags", "casual"}},
        {"Indie", {"tags", "indie"}},
        {"RPG", {"genres", "rpg"}},
        {"Simulation", {"genres", "simulation"}},
        {"Strategy", {"genres", "strategy"}},
        {"Sports", {"genres", "sports"}},
        {"Racing", {"genres", "racing"}},
        {"Horror", {"tags", "horror"}},
        {"Puzzle", {"tags", "puzzle"}},
        {"Platformer", {"tags", "platformer"}},
        {"Fighting", {"tags", "fighting"}},
        {"Shooter", {"genres", "shooter"}},
        {"Free To Play", {"tags", "freegame"}},
        {"Sci-Fi", {"tags", "sci-fi"}},
        {"Fantasy", {"tags", "fantasy"}},
        {"Survival", {"tags", "survival"}},
        {"Stealth", {"tags", "stealth"}},
        {"Sandbox", {"tags", "sandbox"}},
        {"Visual Novel", {"tags", "visual-novel"}},
        {"Roguelike", {"tags", "roguelike"}},
        {"Metroidvania", {"tags", "metroidvania"}},
        {"Souls-like", {"tags", "souls-like"}},
        {"Hack and Slash", {"tags", "hack-and-slash"}},
        {"Beat 'em Up", {"tags", "beat-em-up"}},
        {"Shoot 'em Up", {"tags", "shoot-em-up"}},
        {"First-Person Shooter", {"tags", "fps"}},
        {"Tower Defense", {"tags", "tower-defense"}},
        {"City Builder", {"tags", "city-builder"}},
        {"Management", {"tags", "management"}},
        {"Crafting", {"tags", "crafting"}},
        {"Base Building", {"tags", "base-building"}},
        {"Turn-Based", {"tags", "turn-based"}},
        {"Real-Time Strategy", {"tags", "rts"}},
        {"Grand Strategy", {"tags", "grand-strategy"}},
        {"4X", {"tags", "four-x"}},
        {"Tactical", {"tags", "tactical"}},
        {"JRPG", {"tags", "jrpg"}},
        {"CRPG", {"tags", "crpg"}},
        {"Tactical RPG", {"tags", "tactical-rpg"}},
        {"Dungeon Crawler", {"tags", "dungeon-crawler"}},
        {"Card Game", {"tags", "card-game"}},
        {"Board Game", {"tags", "board-game"}},
        {"Point & Click", {"tags", "point-and-click"}},
        {"Hidden Object", {"tags", "hidden-object"}},
        {"Walking Simulator", {"tags", "walking-simulator"}},
        {"Rhythm", {"tags", "rhythm"}},
        {"Party Game", {"tags", "party-game"}},
        {"Farming", {"tags", "farming"}},
        {"Life Sim", {"tags", "lifesim"}},
        {"Dating Sim", {"tags", "dating-sim"}},
        {"Fishing", {"tags", "fishing"}},
        {"Physics", {"tags", "physics"}},
        {"Match 3", {"tags", "match-three"}},
        {"Text-Based", {"tags", "text-based"}},
        {"Arcade", {"tags", "arcade"}},
        {"FMV", {"tags", "fmv"}},
        {"Team Sports", {"tags", "team-sport"}},
        {"Flight", {"tags", "flight"}},
        {"Trains", {"tags", "trains"}},
        {"Naval", {"tags", "naval"}},
        {"Tanks", {"tags", "tanks"}},
        {"Co-op", {"tags", "local-co-op"}},
        {"Multiplayer", {"tags", "multiplayer"}},
        {"VR", {"tags", "vr"}},
        {"Open World", {"tags", "open-world"}},
        {"Exploration", {"tags", "exploration"}},
        {"Story Rich", {"tags", "story-rich"}},
        {"Mystery", {"tags", "mystery"}},
        {"Crime", {"tags", "crime"}},
        {"Cyberpunk", {"tags", "cyberpunk"}},
        {"Post-Apocalyptic", {"tags", "post-apocalyptic"}},
        {"Space", {"tags", "space"}},
        {"Medieval", {"tags", "medieval"}},
        {"Historical", {"tags", "historical"}},
        {"War", {"tags", "war"}},
        {"Western", {"tags", "western"}},
        {"Pirates", {"tags", "pirates"}},
        {"Zombies", {"tags", "zombies"}},
        {"Supernatural", {"tags", "supernatural"}},
        {"Lovecraftian", {"tags", "lovecraftian"}},
        {"Steampunk", {"tags", "steampunk"}},
        {"Superhero", {"tags", "superhero"}},
        {"Mythology", {"tags", "mythology"}},
        {"Robots", {"tags", "robots"}},
        {"Dinosaurs", {"tags", "dinosaurs"}},
        {"Animals", {"tags", "cats"}},
        {"Nature", {"tags", "nature"}},
        {"Underwater", {"tags", "underwater"}},
        {"Martial Arts", {"tags", "martial-arts"}},
        {"Time Travel", {"tags", "time-manipulation"}},
        {"Romance", {"tags", "romance"}},
        {"Educational", {"tags", "education"}},
        {"Comedy", {"tags", "comedy"}},
        {"Cozy", {"tags", "cozy"}},
        {"Dark", {"tags", "dark"}},
        {"Atmospheric", {"tags", "atmospheric"}},
        {"Difficult", {"tags", "difficult"}},
        {"Female Protagonist", {"tags", "female-protagonist"}},
        {"LGBTQ+", {"tags", "lgbtq-plus"}},
        {"Family Friendly", {"tags", "family-friendly"}},
        {"2D", {"tags", "two-dimensional"}},
        {"First-Person", {"tags", "first-person"}},
        {"Third-Person", {"tags", "third-person"}},
        {"Top-Down", {"tags", "top-down"}},
        {"Isometric", {"tags", "isometric"}},
        {"Pixel Graphics", {"tags", "pixel-graphics"}},
        {"Retro", {"tags", "retro"}},
        {"Cartoony", {"tags", "cartoony"}},
        {"Realistic", {"tags", "realistic"}},
        {"Gore", {"tags", "gore"}},
        {"Violent", {"tags", "violent"}},
        {"Nudity", {"tags", "nudity"}},
        {"Sexual Content", {"tags", "sexual-content"}},
        // "Massively Multiplayer", "Early Access" and the like have no GOG
        // equivalent (GOG expresses early access via `releaseStatuses`,
        // which GogCandidateFinder doesn't use for genre discovery).
    };
    return t;
}

} // namespace

QString GogGenreMap::toCanonical(const QString& gogLabel)
{
    const QString trimmed = gogLabel.trimmed();
    const auto it = labelTable().find(trimmed.toLower());
    return it != labelTable().end() ? it.value() : trimmed;
}

std::optional<QString> GogGenreMap::canonicalIfKnown(const QString& gogLabel)
{
    const auto it = labelTable().find(gogLabel.trimmed().toLower());
    if (it == labelTable().end())
        return std::nullopt;
    return it.value();
}

std::optional<GogGenreMap::CatalogFilter> GogGenreMap::catalogFilterFor(const QString& canonicalGenre)
{
    const auto it = filterTable().find(canonicalGenre);
    if (it == filterTable().end())
        return std::nullopt;
    return it.value();
}

} // namespace ssv
