#include "sources/GenreTaxonomy.h"

namespace ssv {

const QStringList& GenreTaxonomy::canonicalGenres()
{
    // The shared canonical vocabulary every source maps its own genres/tags
    // onto (see SteamGenreMap, GogGenreMap, IgdbGenreMap). It started as
    // Steam's official store genres and now also covers the sub-genres,
    // themes, settings, perspectives and content tags Steam and GOG expose
    // as user tags, so a filter can express "roguelikes" or "cozy games",
    // not just "Action". The first 23 entries are the original list; the
    // order of the rest is the order the settings dialog shows them in.
    static const QStringList genres{
        QStringLiteral("Action"),
        QStringLiteral("Adventure"),
        QStringLiteral("Casual"),
        QStringLiteral("Indie"),
        QStringLiteral("RPG"),
        QStringLiteral("Simulation"),
        QStringLiteral("Strategy"),
        QStringLiteral("Sports"),
        QStringLiteral("Racing"),
        QStringLiteral("Horror"),
        QStringLiteral("Puzzle"),
        QStringLiteral("Platformer"),
        QStringLiteral("Fighting"),
        QStringLiteral("Shooter"),
        QStringLiteral("Massively Multiplayer"),
        QStringLiteral("Free To Play"),
        QStringLiteral("Early Access"),
        QStringLiteral("Sci-Fi"),
        QStringLiteral("Fantasy"),
        QStringLiteral("Survival"),
        QStringLiteral("Stealth"),
        QStringLiteral("Sandbox"),
        QStringLiteral("Visual Novel"),
        QStringLiteral("Roguelike"),
        QStringLiteral("Metroidvania"),
        QStringLiteral("Souls-like"),
        QStringLiteral("Hack and Slash"),
        QStringLiteral("Beat 'em Up"),
        QStringLiteral("Shoot 'em Up"),
        QStringLiteral("First-Person Shooter"),
        QStringLiteral("Third-Person Shooter"),
        QStringLiteral("Battle Royale"),
        QStringLiteral("Tower Defense"),
        QStringLiteral("City Builder"),
        QStringLiteral("Management"),
        QStringLiteral("Crafting"),
        QStringLiteral("Base Building"),
        QStringLiteral("Turn-Based"),
        QStringLiteral("Real-Time Strategy"),
        QStringLiteral("Grand Strategy"),
        QStringLiteral("4X"),
        QStringLiteral("Tactical"),
        QStringLiteral("JRPG"),
        QStringLiteral("CRPG"),
        QStringLiteral("Action RPG"),
        QStringLiteral("Tactical RPG"),
        QStringLiteral("Dungeon Crawler"),
        QStringLiteral("Card Game"),
        QStringLiteral("Board Game"),
        QStringLiteral("Point & Click"),
        QStringLiteral("Hidden Object"),
        QStringLiteral("Walking Simulator"),
        QStringLiteral("Rhythm"),
        QStringLiteral("Party Game"),
        QStringLiteral("Farming"),
        QStringLiteral("Life Sim"),
        QStringLiteral("Dating Sim"),
        QStringLiteral("Fishing"),
        QStringLiteral("Physics"),
        QStringLiteral("Match 3"),
        QStringLiteral("Text-Based"),
        QStringLiteral("Incremental"),
        QStringLiteral("Creature Collector"),
        QStringLiteral("Arcade"),
        QStringLiteral("MOBA"),
        QStringLiteral("God Game"),
        QStringLiteral("Immersive Sim"),
        QStringLiteral("FMV"),
        QStringLiteral("Team Sports"),
        QStringLiteral("Flight"),
        QStringLiteral("Trains"),
        QStringLiteral("Naval"),
        QStringLiteral("Tanks"),
        QStringLiteral("Co-op"),
        QStringLiteral("Multiplayer"),
        QStringLiteral("VR"),
        QStringLiteral("Open World"),
        QStringLiteral("Exploration"),
        QStringLiteral("Story Rich"),
        QStringLiteral("Mystery"),
        QStringLiteral("Crime"),
        QStringLiteral("Cyberpunk"),
        QStringLiteral("Post-Apocalyptic"),
        QStringLiteral("Space"),
        QStringLiteral("Medieval"),
        QStringLiteral("Historical"),
        QStringLiteral("War"),
        QStringLiteral("Western"),
        QStringLiteral("Pirates"),
        QStringLiteral("Zombies"),
        QStringLiteral("Supernatural"),
        QStringLiteral("Lovecraftian"),
        QStringLiteral("Steampunk"),
        QStringLiteral("Superhero"),
        QStringLiteral("Anime"),
        QStringLiteral("Mythology"),
        QStringLiteral("Robots"),
        QStringLiteral("Dinosaurs"),
        QStringLiteral("Animals"),
        QStringLiteral("Nature"),
        QStringLiteral("Underwater"),
        QStringLiteral("Martial Arts"),
        QStringLiteral("Time Travel"),
        QStringLiteral("Romance"),
        QStringLiteral("Educational"),
        QStringLiteral("Comedy"),
        QStringLiteral("Cozy"),
        QStringLiteral("Dark"),
        QStringLiteral("Atmospheric"),
        QStringLiteral("Difficult"),
        QStringLiteral("Female Protagonist"),
        QStringLiteral("LGBTQ+"),
        QStringLiteral("Family Friendly"),
        QStringLiteral("2D"),
        QStringLiteral("3D"),
        QStringLiteral("First-Person"),
        QStringLiteral("Third-Person"),
        QStringLiteral("Top-Down"),
        QStringLiteral("Isometric"),
        QStringLiteral("Side Scroller"),
        QStringLiteral("Pixel Graphics"),
        QStringLiteral("Retro"),
        QStringLiteral("Cartoony"),
        QStringLiteral("Realistic"),
        QStringLiteral("Gore"),
        QStringLiteral("Violent"),
        QStringLiteral("Nudity"),
        QStringLiteral("Sexual Content"),
    };
    return genres;
}

bool GenreTaxonomy::isCanonical(const QString& genre)
{
    return canonicalGenres().contains(genre, Qt::CaseInsensitive);
}

} // namespace ssv
